### ISSUE TITLE
Task Center - My Requests && My Tasks: Arabic name is mandatory but not shown, and if English name is not filled it will show the task with no title 

### ISSUE THREAD

**Issue by DemaHamideh** [MasterteamSA/Riyadh_Municipality_PPlus#42]
Steps: 

1. from test4 add new task assigned to epm from my requests tab 
2. fill Arabic with Arabic names and English name with English name 
3. in addition, try to fill Ar and keep En empty 

Actual Result: 

1. adding the task name in Arabic is mandatory, but after adding it, it show only task in English for both Ar and En version 

![image](https://user-images.githubusercontent.com/110157969/193559262-ff1eb9af-9309-45b1-a454-a67598db99bb.png)

![image](https://user-images.githubusercontent.com/110157969/193560361-62e02961-1731-4bc6-b423-604624dd3247.png)

2. keep the En empty, will lead to show task with empty title 

![image](https://user-images.githubusercontent.com/110157969/193559981-5827cf17-6837-410e-8a1d-4431845abc26.png)

![image](https://user-images.githubusercontent.com/110157969/193560037-5367dd34-9e0c-4d27-83e1-44d167088c24.png)

![image](https://user-images.githubusercontent.com/110157969/193560645-75446b3a-699e-4e08-9b4a-eb0cbc91e415.png)

**Comment by JarrarMo** [comment]
@ealtiti Kindly check the mapping

**Comment by ealtiti** [comment]
@JarrarMo  this is vanilla version 

fixed 
<img width="1408" alt="Screen Shot 2022-10-04 at 11 04 56 AM" src="https://user-images.githubusercontent.com/85454412/193767257-4ce600c7-45d7-4c01-b0e6-62797f70557f.png">
<img width="1408" alt="Screen Shot 2022-10-04 at 11 04 59 AM" src="https://user-images.githubusercontent.com/85454412/193767266-8affe3f8-1bfb-45b8-b7e5-3522d2a0db80.png">

**Comment by DemaHamideh** [comment]
1. now in "MY REQUESTS" &&& "MY TASKS" tabs, in AR version, when click on the task to open the details, it will show the English title instead of the Arabic title 


https://user-images.githubusercontent.com/110157969/193833599-e218bd34-dcc5-4b6c-a0ce-2b584d353f9f.mp4


2. the second case is not solved "try to fill Ar and keep En empty", after adding a task with empty En, it will be shown as null 

![image](https://user-images.githubusercontent.com/110157969/193835100-03de210d-b3dc-4edb-be96-0064fd43779d.png)

**Comment by ealtiti** [comment]
<img width="1428" alt="Screen Shot 2022-10-04 at 4 53 30 PM" src="https://user-images.githubusercontent.com/85454412/193840413-c7de9fef-38b1-4ba1-b66d-6b3d691f3cc4.png">
<img width="1428" alt="Screen Shot 2022-10-04 at 5 03 41 PM" src="https://user-images.githubusercontent.com/85454412/193840452-a6257836-deeb-43c7-b465-154d9836ac6a.png">

**Comment by DemaHamideh** [comment]
Approvals Tab: 

The title still appears as null in both AR and EN versions, because the task was added with AR title only 

![image](https://user-images.githubusercontent.com/110157969/194009294-a3380601-7d35-41a9-b842-8b0f40aec9a5.png)


![image](https://user-images.githubusercontent.com/110157969/194009390-3ee88118-8fc4-43a7-994c-248dff32df7c.png)

**Comment by ealtiti** [comment]
<img width="1428" alt="Screen Shot 2022-10-05 at 11 40 12 AM" src="https://user-images.githubusercontent.com/85454412/194018458-e4e95f2e-a4d8-4086-881b-80348bed75bf.png">
<img width="1428" alt="Screen Shot 2022-10-05 at 11 40 20 AM" src="https://user-images.githubusercontent.com/85454412/194018466-318694a2-b59c-4651-8769-d75b118d5961.png">

**Comment by DemaHamideh** [comment]
still have the below in the approval tab: 
when the Ar title exists, and the user clicks on the task to show the details, the En title that will appear 


https://user-images.githubusercontent.com/110157969/194233543-d193a703-79f1-49b9-91c7-c74edc053246.mp4

**Comment by ealtiti** [comment]
<img width="1432" alt="Screen Shot 2022-10-27 at 10 27 20 AM" src="https://user-images.githubusercontent.com/85454412/198218465-2e99af85-cb54-45de-9e96-536cf46b7193.png">

**Comment by DemaHamideh** [comment]
Fixed
